
spring:
    security: 
        oauth2:
            client:
                registration:
                    github:
                        clientId: xxx
                        clientSecret: xxx
server:
    port: 8080
    address: 127.0.0.1